### ISSUE TITLE
DDette er en feil

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/altinn-infoportal-optimizely#1]
### Description of the bug

Beskrivelse

### Steps To Reproduce

sdsdf

**Comment by borresundberg** [comment]
test

**Comment by altinnservicedesktest** [comment]
Kan en bruker som ikke har direkte tilgang legge til en kommentar på en lukket sak?

**Comment by tommyalmendingen** [comment]
Ja det kan du visst.  😄
