### ISSUE TITLE
Monitorering av endepunkter inn mot Optimizely DXP

### ISSUE THREAD

**Issue by borresundberg** [Altinn/altinn-infoportal-optimizely#11]
### Description

Finnes det noen form for monitorering av endepunkter inn mot Optimizely DXP som kan fungere som gode helsesjekker inn mot de ulike miljøene?  
Spørsmålet kommer fra Orange og kan være smart å ha ift overvåking fra både Accenture og Orange sin side for å vite status.

### In scope

Dokumentere evt endepunkter og hvordan disse kan overvåkes eksternt.

### Out of scope

Kun en forespørsel og ingen implementering ennå dersom dette ikke finnes

**Comment by oyvindwh** [comment]
Optimizely har ingen endepunkt for overvåking. Vanlig prosedyre er en forespørsel mot startsiden og verifisere responsen (200 OK status code).
