### ISSUE TITLE
Manglende oversettelser i Episerver-grensesnittet

### ISSUE THREAD

**Issue by davidsenkristoffer** [Altinn/altinn-infoportal-optimizely#12]
### Description of the bug

Det er kommet en del nye felter på søkesiden som ikke har fått oversettelser på norsk og engelsk.

### Steps To Reproduce

Logg inn i Episerver-grensesnittet.
Gå til siden 'Søk'.
Observer at feltene ikke har oversettelser.

**Comment by davidsenkristoffer** [comment]
Testinstruksjon:

Gå til Startside > Søk i Episerver-grensesnittet. Sjekk at feltene har fått oversettelse på norsk og engelsk. Hvis du bare får engelsk (som er fallbackverdien), verifiser at språket i Episerver er satt til norsk. Dette kan endres ved å gå til brukerinnstillinger oppe i høyre hjørne i grensesnittet.

**Comment by ferkinx** [comment]
@davidsenkristoffer Her må jeg ha litt voksenopplæring. Kan vi ta et kjapt møte hvor du viser meg problemet her...

**Comment by davidsenkristoffer** [comment]
Det er disse feltene som skal ha oversettelse. 

![altinn28127](https://github.com/Altinn/altinn-infoportal-optimizely/assets/88896307/9ee2a8cf-f1c5-4b04-b956-34b0a271c1df)
