### ISSUE TITLE
Filter på søk

### ISSUE THREAD

**Issue by thordfoss** [Altinn/altinn-infoportal-optimizely#128]
## Kontekst
Har sett noen utfordringer med filtrering på dagens sider:

- Filtrering på mobil bygger særlig mye. Hvor mye blir den brukt? Kan vi droppe den? Skjule den  legge opp til horisontal scroll?
- Usikker på om filter-knappene er helt intuitiv. Mulig vi bør bytte til mer standard sjekk-bokser. Har vi noe i designsystemet?
- Linjen med antall treff kommer over filterne. Det gir mer mening å gruppere filterne med fanene for innboks og infoportal.
- Skjema er forhåndsfiltrert når du søker fra alle skjema. Det er en fare for at sluttbruker overser denne filtreringen. Det vil være mer i tråd med beste praksis å vise en komplett treffliste først og la brukeren selv velge hva hen vil filtrere på.ett til «søk på tvers».
- I linjen som viser antall treff blir filtreringen kun vist i tekst. (2 treff i starte og drive bedrift) Tror visuell hjelp vil gjøre filterne mer umiddelbart forståelig.
- Bug: Når du filtrerer på «starte og drive bedrift» får du ikke opp noen treff, selv om det står (2)
- Velger du fanen «innboks» sendes du til aktørvalg, og må velge/gjette hvilken innboks du bør søke i. Hvis vi skal opprettholde dette burde vi kanskje sende brukeren rett til søk på tvers.

## Forslag til justeringer

- [ ] Filter skjult på mobil. Vises i horisontal scroll.
- [ ] Linjen med antall treff under filterne. 
- [ ] Ingen forhåndsfiltrering
- [ ] Viser filtertreff som etikett i linjen med antall treff
- [ ] Sende bruker til “søk på tvers” når sluttbruker søker i innboks.

Se skissene her:
https://www.figma.com/file/woxVHUL7DYOWSQ9A8MMFGV/S%C3%B8k-i-info.altinn.no?type=design&node-id=19%3A24646&mode=design&t=FQItDYMmNkJsPLTp-1

**Comment by monicaolsen** [comment]
@thordfoss @dortedrange Denne oppgaven kan nå testes her: https://prep.info.altinn.no/

**Comment by thordfoss** [comment]
Hei! Så bra det ble!
To små ting. 
1. Når man scroller horisontalt på mobil, lurer jeg på om "avgrens" også kan følge med her. Slik at du "scroller" hele den linjen. (Tror også vi kan endre "avgens treffene" til "avgrens for å spare litt plass.
2. Har ikke sjekket alle nettlesere, men på safari på mac!en får filterne en "falsk bold"

**Comment by thordfoss** [comment]
<img width="1072" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/12525344/450ebcfa-3f18-47ef-93de-f1f26ef2ad32">
Safari
<img width="824" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/12525344/bb0a772f-e72f-4642-b23a-84a201c8ecc8">
Chrome

**Comment by monicaolsen** [comment]
@thordfoss Jeg har fikset feilene du fant. Kan du teste igjen og gi tilbakemelding? :) Jeg ser at det er noen små forskjeller på fonten i chrome vs. safari selv om samme font brukes i koden. Jeg syntes det ble bra nå men kan godt se nærmere på fonter senere hvis du vil det. https://prep.info.altinn.no/

**Comment by thordfoss** [comment]
@monicaolsen Ser bra ut nå! Jeg tenker den er klar
