### ISSUE TITLE
Justeringer på altinn.no/hjelp

### ISSUE THREAD

**Issue by thordfoss** [Altinn/altinn-infoportal-optimizely#136]
**Kontekst**
1. Illustrasjonen skyver ned inngangene til hjelpe-artiklene og fremhever søkefeltet mer enn nødvendig. Dette skjer Særlig på mindre skjermer og når hjelpesidene lenkes til fra Altinn 2-tjenester. (se notasjon 4)
2. Placeholderteksten i søkefeltet kan oppleves misvisende. Vi har ikke oversikt over omfanget, men ser i søkeloggen at enkelte skriver inn spørsmål som tyder på at det oppleves som en chat.
3. Store ikoner og mye “luft” tar mye plass på mobil.

**Forslag**
1. Endre på bakgrunn. Ny bakgrunn kan følge samme høyde, format og farge som på søketreff på hjelp.
2. Endre placeholdertekst til Søk i hjelpesidene.
3. Endre hovedinnganger på mobil til listevisning med mindre ikoner og mindre luft.

Skissene ligger her: https://www.figma.com/file/woxVHUL7DYOWSQ9A8MMFGV/S%C3%B8k-i-info.altinn.no?type=design&node-id=416%3A101&mode=design&t=nfvVfW1AhUQwa4Sl-1

**Comment by thordfoss** [comment]
Har pratet med @dortedrange og vi går for denne løsningen, hvis ikke du finner noe som ikke funker @monicaolsen :)

**Comment by ferkinx** [comment]
Denne er nå i prod. :)
