### ISSUE TITLE
Manifest.json mangler

### ISSUE THREAD

**Issue by HenningNormann** [Altinn/altinn-infoportal-optimizely#14]
Chrome prøver å finne https://www.altinn.no/Static/favicon/manifest.json. Denne referansen gir p.t. 404. https://www.altinn.no/Static/favicon/manifest.json finnes, så det virker som noe ikke er med over i ny løsning.

**Comment by davidsenkristoffer** [comment]
PR: https://dev.azure.com/digdir/altinn-infoportal/_git/altinn-infoportal/pullrequest/6476

**Comment by benjamfi** [comment]
Endring er deployet til integration.

**Comment by davidsenkristoffer** [comment]
Testinstruksjon:

manifest.json kan nås her: https://prod.altinn.cloud/Static/favicon/manifest.json

**Comment by ferkinx** [comment]
Ser riktig ut for meg (som ikke skjønner så mye av det), men ser at faviconene er på plass i browser-fanene iallfall :)
