### ISSUE TITLE
Legge inn Monsido-script

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#144]
Siteimprove tapte anbudet, så fra 12. desember får vi ikke lenger analytics/WCAG-overvåking/SEO etc. fra dem. 

Derfor haster det med å få lagt inn JS fra vår nye leverandør - Monsido. 

Ønsker følgende script fra Monsido lagt inn på sidene i Infoportalen asap:

<script type="text/javascript">
    window._monsido = window._monsido || {
        token: "fsJh2cWUHD1WKzBtolnR3A",
        statistics: {
            enabled: true,
            cookieLessTracking: true,
            documentTracking: {
                enabled: true,
                documentCls: "monsido_download",
                documentIgnoreCls: "monsido_ignore_download",
                documentExt: [],
            },
        },
        heatmap: {
            enabled: true,
        },
    };
</script>
<script type="text/javascript" async src="https://app-script.monsido.com/v2/monsido-script.js"></script>

**Comment by WilhelmKXO** [comment]
Til oppdatering: for å gi mulighet til å teste forskjellige varianter av skriptet ble det besluttet å legge inn et skript felt på startsiden slik at redaktører kan gjøre endringer når det er behov. Istedenfor å gå igjennom utvikling hver gang.
