### ISSUE TITLE
Digitaliseringsdirektoratet og adresse skal stå på engelsk i footer når man har valgt engelsk språkkanal

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#159]
### Description of the bug

Det er bare mulig å legge inn norsk versjon av etatsnavn og -adresse i footer i Infoportalen:
<img width="1097" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/959c4bae-5c6a-4cf6-9219-3ef603e21833">

I sidemalen for startsiden må det være mulig å legge inn engelsk etatsnavn og adresse - dette er nå grået ut i input-feltene når man velger engelsk i CMS-et. Disse feltene må være redigerbare i alle språkversjoner av siden - også telefonnr.-feltet (så det går an å legge inn +47 for andre språk enn norsk).

<img width="1464" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/657228a8-5044-4272-aeab-ee8c7fe12b5d">

### Steps To Reproduce

Se over

**Comment by WilhelmKXO** [comment]
Lagt til culturespecific på disse feltene slik at de er kan oversettes. Dette må en redaktør da legge inn, hvis ikke er feltet tomt på siden.

**Comment by ferkinx** [comment]
Testet ok
