### ISSUE TITLE
Mangler robots.txt-fil 

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#17]
### Description of the bug

Må lastes opp robots.txt-fil til https://prod.altinn.cloud (som i dag ligger på www.altinn.no/robots.txt). Denne skal ligge på rotnivå.

### Steps To Reproduce

Etter at filen er lastet opp, må det testes at filen ligger på https://prod.altinn.cloud/robots.txt

**Comment by davidsenkristoffer** [comment]
PR: https://dev.azure.com/digdir/altinn-infoportal/_git/altinn-infoportal/pullrequest/6475

**Comment by benjamfi** [comment]
Endring er deployet til integration.

**Comment by davidsenkristoffer** [comment]
@ferkinx Hvor ligger denne filen i dagens løsning? Den ligger ikke i kodebasen for Infoportal.

**Comment by RuneSMarhaug** [comment]
C:\intepub\AltinnEPI\Robots.txt er lokasjon for dagens løsning i PROD.

**Comment by ferkinx** [comment]
Ser at det er lagt inn en robots.txt-fil, men den er ganske tom. Kan dere legge inn følgende i robots.txt-filen:

# 
# robots.txt for https://www.altinn.no/ 
# 
# $Id: robots.txt,v 1.1 2013/07/01 $ 
# 
# exclude pages that require the user to be logged on 
User-agent: * 
Disallow: /ega/
Disallow: /egaagencies/
Disallow: /Pages/
Disallow: /pages/
Disallow: /ui/
# exclude ie. print versions of pages and other frontend stuff
Disallow: /templates/
Disallow: /Frontend/
Disallow: /ip/
Disallow: /autoscripts/
Disallow: /404-side/
Disallow: /nn/oi-du-har-provd-a-komme-til-en-side-vi-ikke-vet-om/
Disallow: /en/error-404/

**Comment by davidsenkristoffer** [comment]
Testinstruksjon:

robots.txt kan redigeres ved å gå til Episerver-grensesnittet > Admin > 'Manage robots.txt content' under fanen Verktøy. 
Denne må regenereres når vi bytter domene ved prodsetting, så det kan nok legges til som et steg i prodsettingsplanen @borresundberg .

https://prod.altinn.cloud/robots.txt

**Comment by ferkinx** [comment]
Suverent at du la inn redigeringsmulighet i Admin, Kristoffer - godt levert!
