### ISSUE TITLE
SubsidyOverViewPage JS feiler

### ISSUE THREAD

**Issue by WilhelmKXO** [Altinn/altinn-infoportal-optimizely#182]
https://digi03mstrrk51ointe.dxcloud.episerver.net/starte-og-drive/stotteordninger/

Console feil. 

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/f76c271b-aa1f-4db3-a874-00890e3bf261)

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/a07bbf62-e425-4445-89a9-a1d5a7b77c19)

**Comment by monicaolsen** [comment]
@WilhelmKXO Her får jeg 404 error lokalt så får ikke testet. Men ser i testmiljøet at problemet mest sannsynlig er samme som søkeresultater med feil casing i response dataen. Hvis du kan hjelpe meg med å få respons fra api lokalt så skal jeg finne ut av det :)

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147140002/271fd587-6164-4a2c-9e2d-407ad915d7a4)

**Comment by WilhelmKXO** [comment]
Er ordnet i branchen upgrade/subsidyOverview
