### ISSUE TITLE
Søkeresultater vises ikke

### ISSUE THREAD

**Issue by WilhelmKXO** [Altinn/altinn-infoportal-optimizely#183]
![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/42a30597-78e6-4bdb-a031-35456fc60665)

**Comment by monicaolsen** [comment]
@WilhelmKXO @JonasHildershavnKnowit Kan se ut som en gjengående feil er at frontend forventer annen casing enn det som blir sendt fra backend nå. "ResultType" vs "resultType". Er vel egentlig camelCase som burde ha vært brukt fra start, så vi får gå gjennom og sjekke :) 
I tillegg mottar ikke frontend all data for søkeresultater nå som fører til "undefined".  Jeg har fikset så listen faktisk rendres i denne branchen: feature/search-result-bugfix, fint om en av dere kan se på hvorfor frontend bare mottar "resultType"

Lokalt (https://localhost:53981/sok/?q=test):
![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147140002/90bd6f55-1ec7-4c9a-960e-42d75d15d23f)


Testmiljø (https://inte.info.altinn.no/sok/?q=test):
![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147140002/8d7994e9-6a34-40da-81e9-6a33234c1ca5)
