### ISSUE TITLE
Søkespørringer skaper indekserbare sider på Google - foreslår noindex

### ISSUE THREAD

**Issue by siljetjomlid** [Altinn/altinn-infoportal-optimizely#185]
For en stund siden (november) oppdaget vi et problem med autogenererte søke-URLer og at disse ble indeksert. Dette har blitt brukt til spamdexing, se skjermbilde.
Jeg har tidligere diskutert dette med Wilhelm og Børre, og vi har implementert disallow i robots.txt og håpet på det beste. 

Når jeg sjekker igjen, ser jeg at vi fremdeles har dette problemet. Det er ikke like mange indekserte sider, men de finnes fortsatt.
Jeg vil derfor foreslå å implementere noindex på alle søkegenererte URLer.

Legge til <meta name="robots" content="noindex"> i <head> for alle søkeresultatsider.
[Google dokumentasjon.](https://developers.google.com/search/docs/crawling-indexing/block-indexing)

![image (4)](https://github.com/Altinn/altinn-infoportal-optimizely/assets/148449137/7060f1b0-c748-4223-aaee-6a12bfce943f)

**Comment by ferkinx** [comment]
Flytter denne til In-progress så vi kan få den fikset sammen med andre SEO-issues :)
