### ISSUE TITLE
Feil i frontend-kode i accordion - trekkspill-navigasjon på Om-skjema-sidene

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#210]
### Description of the bug

Denne feilen gjør at flere søkemotorer - både AI-baserte og tradisjonelle - ikke finner innhold som ligger under trekkspillnavigasjonen på Om-skjema-sidene, f.eks. under "Hvem skal levere", "Mer om skjema", etc.

Feilen ble egentlig påvist av Siteimprove før vi gikk over til Monsido (som IKKE påviser feilen). Her er skjermdump av kommentaren fra Siteimprove:

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/002534ce-d386-4631-95d3-38a2ca6af885)

Ber om at denne feilen prioriteres helt på topp etter prod.setting av CMS-12, siden det er veldig dumt at AI-søk ikke finner innholdet.

Kan dette være en potensiell løsning: https://github.com/Altinn/altinn-studio-docs/issues/1656 ?
Eller kanskje det er flere alternativer basert på ARIA attributter som kan også løse det, og da kanskje med enda bedre kontroll?

(Denne feilen har vi diskutert på mail og på Slack i februar, og jeg trodde det lå en issue inne, men finner den ikke.)

### Steps To Reproduce

Vanskelig å reprodusere, men vi har erfart det ved test av AI-søkemotoren Raffle og Altinn sin AI-assistent.

**Comment by ferkinx** [comment]
@monicaolsen Kan du beskrive hva som er gjort her - og hvordan jeg ev. kan teste det?

**Comment by monicaolsen** [comment]
@ferkinx 
Her har jeg gjort endringer i html strukturen, i hovedsak byttet ut <a> element med <button> som er semantisk riktig. Gjerne sjekk at accordions oppfører seg likt som før. Eksempel: https://prep.info.altinn.no/skjemaoversikt/bronnoysundregistrene/registrere-reelle-rettighetshavere/

Du kan også sjekke siteimprove, nå er vi nede i 18 forekomster i integration miljøet: https://my2.siteimprove.com/Accessibility/1211644/NextGen/Issue/1?conformance=0,1&siteTargetIssueKinds=1,2&wcagVersion=21&pageSegments=&ruleName=sia-r90&ruleId=90&issueKind=1&exceptTags=1,2&siteTarget.wcagVersion=21&siteTarget.conformanceLevels=0,1&siteTarget.issueKinds=1,2&siteTarget.wcagVersion=21&siteTarget.conformanceLevels=0,1&siteTarget.issueKinds=1,2 

Det betyr at jeg har misset et par steder hvor accordion blir brukt men skal finne ut av det :)

**Comment by ferkinx** [comment]
@monicaolsen  
Det er jo supert at en så enkel endring gjør at Siteimprove ikke regner dette som en feil lenger, men har du sett på anbefalt kode for Accordion-meny i Digdir sitt designsystem - se https://next.storybook.designsystemet.no/?path=/docs/komponenter-accordion--docs

Jeg synes det ser ut til at forslaget til frontend-kode i designsystemet ser mye enklere og mer semamtisk ut enn koden i INTE og PREP:

![Image](https://github.com/user-attachments/assets/ec98f22f-ac0b-4cf7-91f5-724389912660)

I koden over, forstår til og med jeg hva som skjer, men ikke her:

![Image](https://github.com/user-attachments/assets/0aac034e-b604-4e19-a58b-9e1a96e482bb)

Er det noe i veien for å gjøre frontend-koden i Infoportalen mer i samsvar med anbefalingene i designsystemet?

**Comment by ferkinx** [comment]
Er prod.satt i dag :)
