### ISSUE TITLE
SØK - får null treff ved søk på engelsk

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#22]
### Description of the bug

Feilen gjelder i uavhengig av hvilken språkkanal som er valgt.
Søk på "company" eller "sole proprietorship" gir null treff

### Steps To Reproduce

Søk fra hvilket som helst søkefelt (forsiden, skjemakatalog, starte og drive eller hjelpesidene) på f.eks. Company.

**Comment by benjamfi** [comment]
Fikses sammen med #23 som forbedrer språkfiltrering.

**Comment by benjamfi** [comment]
Kode er deployet til prep. Prøv nå å søke på engelsk.
