### ISSUE TITLE
Teste relative lenker i ulike Altinn miljø mot PREP og PROD

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/altinn-infoportal-optimizely#25]
### Description

Fyll på med bedre beskrivelse etter hvert...

Teste relative lenker inkludert "Logg inn" knappen i ulike miljøer. 

Kort beskrivelse for sluttbukerdel:
- Logg inn i testmiljø
- Gå til innboks
- Gå til forside
- Gå til skjemakatalog og se på ulike skjema
- Gå gjerne frem og tilbake mellom innlogget og ikke innlogget del
- Logg og og verifiser at man kommer tilbake til rett miljø

For redaktøredel:
- Foreta en endring i PREP
- Sjekk at endringer vises i aktuelt miljø

### Tasks

Fra https://prep.altinn.cloud/
- [x] AT05
- [ ] AT21
- [x] AT22
- [ ] AT23
- [ ] AT24
- [x] TT02

Fra https://prod.altinn.cloud/
- [ ] altinn.no

**Comment by ferkinx** [comment]
Testet OK i tre miljøer. Gidder ikke teste i alle. Enten er lenkene relative eller så er de det ikke i PREP.
