### ISSUE TITLE
Feil visning av tekst i treffliste etter søk

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#30]
### Description of the bug

På dagens søketreffliste, vises starten på ingressen under tittelen på siden i trefflista. Det er korrekt og ønsket visning, se fig:

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/dd948b81-858f-4e15-98c4-edac0f71cfed)

I det nye søket i DXP, velges et tilsynelatende tilfeldig tekstutdrag fra brødteksten på siden, se fig:

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/a3abbcf2-cdde-4bc8-b6c2-85c1a8713da3)

Dette må endres slik at det fungerer i dagens løsning.

### Steps To Reproduce

1. Gjør et søk på "firmabil"
2. Sjekk teksten som står under søketreffene. Disse viser et litt tilfeldig tekstutdrag fra treffsiden

**Comment by davidsenkristoffer** [comment]
Denne kan testes i preprod eller prod.

**Comment by ferkinx** [comment]
Testet OK
