### ISSUE TITLE
SØK - "Mente du...."-funksjonalitet

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#31]
### Description

Dette ligger egentlig klart i den nye koden for søket, men krever litt design/frontend-tilpasning. Dvs. at folk får søkeforslag ved feilstavinger etc., slik som f.eks. på regjeringen.no

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/1dbeca51-2f85-494e-9c7e-7c5ee9227263)

**Comment by ferkinx** [comment]
Tror ikke denne trenger innom design - kan gå rett til frontend. Ønsker samme tekst og lenke til foreslått søkeord som på regjeringen.no, men selvsagt med Altinn sin font/fontstørrelse/farge.

**Comment by thordfoss** [comment]
Har satt opp en enkel skisse ihht dagens design her: https://www.figma.com/file/woxVHUL7DYOWSQ9A8MMFGV/S%C3%B8k-i-info.altinn.no?type=design&node-id=1%3A22&mode=design&t=Tpqztg5Jg5sXpUhh-1

**Comment by monicaolsen** [comment]
@thordfoss @ferkinx Stemmer det at listen (nederst på screenshot fra Regjeringen.no) også skal implementeres? "Forslag.. Sjekk at alle ordene er stavet riktig" osv :)

**Comment by monicaolsen** [comment]
@thordfoss Vi diskuterte noen justeringer for denne oppgaven men husker ikke helt hva vi ble enige om. Har du laget en ny oppgave eller beskrivelse noe sted? :)

**Comment by monicaolsen** [comment]
@WilhelmKXO Her trenger jeg litt hjelp med listen med søkeråd når du har tid. Skriver det her så vi ikke glemmer det :)

**Comment by monicaolsen** [comment]
@thordfoss @dortedrange Denne oppgaven kan testes delvis. "Mente du.."-funksjonaliteten er klar, mens listen med søkeråd er ikke gjort enda. Eksempel på søk som viser forslag: https://prep.info.altinn.no/sok/?q=altin
