### ISSUE TITLE
SØK - mulighet for vekting/freshness-decay på innholdsområder

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#34]
### Description of the bug

Tabellen for å kunne vekte og legge inn freshness-decay mangler under søkeinnstillinger i Admin. 

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/da84911a-f33b-427b-be90-3cf5f977dd5f)

Dette er viktig for at søket skal framstå like relevant i Optimizely DXP som dagens søk. (F.eks. er det en halvannet år gammel nyhetssak som kommer på topp når man søker på "skattemeldingen", se https://prod.altinn.cloud/sok/?q=Skattemeldingen). 

Vi kan ikke vekte på sidetyper (siden vi har så få, generiske sidemaler), men må kunne vekte på mapper i sidetreet, som Starte og drive bedrift, Skjemaoversikten, Om Altinn, Hjelp, Nyheter, etc.

### Steps To Reproduce

Se beskrivelsen over...

**Comment by haugsten** [comment]
Har lagt til de sidetypene jeg tror er aktuelle. Si ifra hvis noen mangler.

Kode er sjekke inn så kommer på prep ved neste deploy.

**Comment by ferkinx** [comment]
Viser til chat med Haakon Peder, flere sidetyper mangler for vekting/freshness... Setter til In progress.

**Comment by borresundberg** [comment]
@ferkinx  - hva er status på denne?  Ut i fra kommentaren din over skulle du sette denne til "In progress", men den står nå til "In review".  Hva er korrekt status?
