### ISSUE TITLE
SØK - søket finner sider som ikke skal omfattes av søket

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#35]
### Description of the bug

Brukermanualen for redaktører/admin ligger i sidetreet, og skal ikke omfattes av søket. Det skal heller ikke mappa tekniske sider:

Prøv å søk på det litt spesielle søkeordet "søk": https://prep.altinn.cloud/sok/?q=s%C3%B8k
eller "dll", https://prep.altinn.cloud/sok/?q=dll

<img width="625" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/f4742d53-222d-4308-8587-82c6ad61c3f7">
<img width="952" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/de59ef3c-e0ce-4d28-9636-7c5f32c0a8b3">

<img width="1047" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/1fe7d119-b943-4447-a031-35fda5fa0fff">

### Innholdet i e-guider skal ikke finnes i søk
Gir også treff i enkeltsider i e-guider (skjemasider) som IKKE skal vises i søk.
Eks: Søk på "høner", og klikk på treff nr. 2 "Skal du produsere egne råvarer": https://prod.altinn.cloud/sok/?q=h%C3%B8ner

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/ce2a8bc3-7331-4c91-8684-3e65eb60814d)

### Steps To Reproduce

Se over...

**Comment by davidsenkristoffer** [comment]
Fikser i løpet av dagen @ferkinx , gir en lyd når det kan testes.

**Comment by davidsenkristoffer** [comment]
@ferkinx Denne er i preprod og prod. For å skjule .dll-sidene må det manuelt hukes av for at sidene ikke skal kunne søkes på. Årsaken til dette er at sidene er av typen 'ArticlePage', så vi kan ikke skjule disse på sidetypenivå. Se vedlagte bilde for hvor feltet som skal hukes av ligger:

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/88896307/3cab77df-a7e8-4b37-8689-bd8271817c1d)

**Comment by ferkinx** [comment]
Testet OK (selv om det er noen justeringer vi må få gjort etter  at vi har migrert :))
