### ISSUE TITLE
Treg respons på søk

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#36]
### Description of the bug

kl 18.58 - søk på søkeordet "søk". Responstid ca. 5-6 sekunder
Gjentatte søk etterpå gikk raskere - ca. 1,5 sekund responstid, så det kan ha skyldtes at det var første søk etter deploy eller lign?

Elastic-søket on-prem er uansett mye raskere, men 1,5 sek. er ikke showstopper for endelig migrering.

### Steps To Reproduce

Se over...

**Comment by davidsenkristoffer** [comment]
PR: https://dev.azure.com/digdir/altinn-infoportal/_git/altinn-infoportal/pullrequest/6483

**Comment by benjamfi** [comment]
PR er ok.

**Comment by davidsenkristoffer** [comment]
@ferkinx Denne er nå i preprod og prod. Det er fortsatt rom for optimisering av søket på forskjellige områder, men jeg tenker det er en god start hvertfall.

Jeg har oppdaget et par feil relatert til visning av søkeantall kontra faktiske resultater, jeg fikser dette på mandag.

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/88896307/15d33bdd-9ca4-4404-956c-2f5f8efce5f9)

Over viser et skjermbilde hvor antall resultater er "1", men faktiske resultater er mange flere.

**Comment by davidsenkristoffer** [comment]
I dagens løsning lastes fasetter inn på serverside, mens selve søkeresultatene lastes inn med javascript på klient. Her er det rom for forbedringer ved å redusere antall requests som gjøres mot søkeindeksen, f.eks. ved å laste alt inn med javascript.
