### ISSUE TITLE
SendGrid API Keys

### ISSUE THREAD

**Issue by oyvindwh** [Altinn/altinn-infoportal-optimizely#39]
https://docs.developers.optimizely.com/digital-experience-platform/docs/configuring-the-email-server

Username: "apikey"
Password: API Key generated below
Hostname: smtp.sendgrid.net

Secret on email.

**Comment by davidsenkristoffer** [comment]
Dette er nå lagt inn i både preprod og prod.

**Comment by ferkinx** [comment]
@davidsenkristoffer For å ha det inn med teskje - skal det gå e-post ut fra PREP nå? Dvs. skal vi kunne teste kontaktskjema mot ABS og Bedriftsveiledning?

**Comment by davidsenkristoffer** [comment]
Ja, det er lagt inn smtp-konfigurasjon for Sendgrid så kontaktskjemaet kan testes i preprod @ferkinx

**Comment by ferkinx** [comment]
@davidsenkristoffer Men det er vel Optimizely DXP sin mailserver? Har vi gitt opp å koble opp mot Digdir sin e-postserver i Azure?

Vi kan få GDPR-problemer ved å bruke SendGrid..., dvs. overføring av personopplysninger til USA.

**Comment by oyvindwh** [comment]
@davidsenkristoffer, jeg ser at dere bruker port 465. Vi bruker port 587 i andre prosjekter. Jeg finner ikke port 465 i dokumentasjonen til Optimizely.

Det ser også ut som om det har sneket seg med et space i passordet du har limt inn i DevOps variabelen.  Se skjermbilde:


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/b432ebfa-d059-4431-9be4-9ca4b57b9fba)

**Comment by oyvindwh** [comment]
Anbefaler egentlig at alle settings ligger som variable, her fra et cms12 prosjekt.


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/7b4f2def-f6f3-430f-b856-07a3189ee05e)

**Comment by oyvindwh** [comment]
Jeg endret passordet i DevOps - variabler. 
Jeg endret port for Prep og Prod til 587. 
Jeg endret ikke for Inte siden der ligger det en host som peker på Basefarm (smtp.ai-prod.osl.basefarm.net).

**Comment by borresundberg** [comment]
@ferkinx  - fikk du testet denne ferdig i prod?

**Comment by borresundberg** [comment]
@ferkinx  - setter denne til "In review" som jeg tenker er en mer korrekt status.  Når du har verifisert, så setter du denne til "Done"

**Comment by ferkinx** [comment]
Testet OK. Har fått svar fra både support@altinn.no (ABS) og Starte-og-drive brukerveiledning at e-postene (med vedlegg) er mottatt
