### ISSUE TITLE
Feil referanser i ny Infoportal?

### ISSUE THREAD

**Issue by borresundberg** [Altinn/altinn-infoportal-optimizely#4]
### Description of the bug

Det ser ut til å være en del feil referanser i infoportalen. Det refereres både til [www.altinn.no](http://www.altinn.no/) (i motsetning til at05), prep.altinn.cloud og [dl.episerver.net](http://dl.episerver.net/). Virker som importen ikke er gjort konsistent.  BN feiler fremdeles, men nå på et forsøk på å hente ned https://dl.episerver.net/13.5.8/epi-util/find.js .

### Steps To Reproduce

 Som avtalt setter jeg denne saken til deg @oyvindwh .  Fint om du får svart ut hva som må gjøres med denne saken :-)

**Comment by oyvindwh** [comment]
https://dl.episerver.net/13.5.8/epi-util/find.js brukes av Optimizely Search And Navigation for tracking av søk. Javascriptet lastes fra Optimizely CDN. Skriptet kan legges lokalt om ønskelig, se regjeringen.no. 


Skriptet lastes korrekt på prod.altinn.cloud:
![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/36f04d9e-c361-4bc2-963d-588de944c280)

Når det gjelder referanser til altinn.no så finnes det i koden:


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/d2db3b1c-f18e-4930-a316-590c6465dd25)


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/9d27543c-6d09-42dc-b9d6-e86dca101236)




Og det kan være egenskaper hvor redaktørene har lagt inn lenker til altinn.no.
