### ISSUE TITLE
Kan jeg sette saker direkte til Monica/front-end og andre i teamet?

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#49]
### Question

@WilhelmKXO 
Bør jeg kunne assigne issues direkte til Monica - ev. både til deg og Monica + ev. andre i kjerneteamet/supplerende team?

Kunne f.eks. være ok å bestille bistand direkte fra Silje på SEO/JSON-LD etc.

**Comment by WilhelmKXO** [comment]
Jeg mener du burde kunne assigne ting til Monica og Jonas direkte ja. Har ikke tenkt at Silje skal ha behov for en Github bruker, men om det blir flere saker på henne kan vi høre om vi kan legge henne inn. Får ikke opp Monica eller Jonas i assignment her, skal se på det.

**Comment by JonasHildershavnKnowit** [comment]
Hei!

**Comment by monicaolsen** [comment]
Hallo :)
