### ISSUE TITLE
Mangler blobs

### ISSUE THREAD

**Issue by borresundberg** [Altinn/altinn-infoportal-optimizely#5]
### Description of the bug

Innhold som filer, media ++ mangler.  Må importere blobs fra dagens on-prem EPI-server løsning.  Filene ligger filstien som miljøvariabelen APPDATA peker på. 

EPI-VPP.zip er hentet ut fra dagens produksjonsløsning, lastet opp hos Optimizely support hvor de har importert til prod.altinn.no.  Dette må verifiseres.

### Steps To Reproduce

 .

### Additional Information

Kan du verifisere at blobs har blitt importert korrekt, @oyvindwh ?

**Comment by oyvindwh** [comment]
![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/7be0ec4b-0ab0-48c9-b7ca-734d042524a9)

Bildene ligger i Asset Pane, opplastingen er verifisert.
