### ISSUE TITLE
Sidene er ikke i sync i tt02 og Prep

### ISSUE THREAD

**Issue by GeirHerbertHorn** [Altinn/altinn-infoportal-optimizely#53]
### Description of the bug

Vi opplever at sidene ikke er i sync i TT02 og PREP

### Steps To Reproduce

Går inn på:
https://tt02-pbl.ai.basefarm.net/EPiServer/Cms/#context=epi.cms.contentdata:///71332&viewsetting=viewlanguage:///no
Går inn på Digitaliseringsdirektoratet og velger Testtjeneste
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/105434005/a23f8e10-0ba4-4914-b072-743623cc1202)

Legger inn en oppdatering av Ingress, denne kommer ikke opp i skjemakatalogen:
https://info.tt02.altinn.no/skjemaoversikt/?category=provider&position=71071

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/105434005/f4b2583e-262d-443a-9e19-79ecd4dbff4c)

**Comment by GeirHerbertHorn** [comment]
Bare for å avklare.
Jeg la inn en oppdatering på https://prep.altinn.cloud/episerver/cms og den finner jeg ikke igjen på https://info.tt02.altinn.no/

**Comment by GeirHerbertHorn** [comment]
Laget nå en helt ny side, og den dukket opp etter ca 8 minutter.

Den jeg oppdaterte tidligere er ikke kommet over.

**Comment by tommyalmendingen** [comment]
Akkurat fått bekreftet fra Geir at synk nå fungerer ok så denne saken kan lukkes.
