### ISSUE TITLE
Lenker til "Start tjeneste" i skjemakatalogen feiler i info.tt02.altinn.no

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/altinn-infoportal-optimizely#55]
### Description of the bug

Fra Elaine (via Teams):
Jeg er innlogget i TT02 og skal hente RF-1028 Skattemelding for å sende inn. Men får feilmelding når jeg velger å starte tjenesten:
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/45939254/5b1ea74c-5d17-4d1e-b7e5-5785a4b2c765)

https://info.tt02.altinn.no/skjemaoversikt/skatteetaten/skattemelding-for-formues--og-inntektsskatt----aksjeselskap-mv/

Når jeg nå klikker på start tjeneste kommer dette bildet:
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/45939254/60e4163f-0fd2-4018-8305-a34cc765edc6)
Men når jeg fjerner INFO i URL så får jeg kommet inn på tjenesten.

### Steps To Reproduce

Se over

**Comment by ferkinx** [comment]
Testet OK
