### ISSUE TITLE
Opprette driftsvarsel/nyhetssak/internt og TE

### ISSUE THREAD

**Issue by borresundberg** [Altinn/altinn-infoportal-optimizely#56]
### Description

Må lages nyhetssak med informasjon om flytting av informasjonsportalen til nytt sub-domene.

**Comment by ferkinx** [comment]
- PDF med informasjon er sendt ut til alle tjenesteeiere, hele avdeling BOD, til proffbrukernes organisasjoner og til KDD m.fl.
- Driftsvarsel lagt ut på forsiden av altinn.no
- Driftsvarsel er sendt ut fra altinndigital.no

Gjenstår:
- Legge ut nyhetssak på Altinn.no - gjøres før onsdag kl 10
- Legge ut sak på Intranett i Digdir.
