### ISSUE TITLE
Legge inn riktig domene i Azure AD for pålogging til admin/redaktørgrensesnittet (info.altinn.no)

### ISSUE THREAD

**Issue by borresundberg** [Altinn/altinn-infoportal-optimizely#58]
### Description

@haugsten og @Herskis må sammen få lagt inn riktig domene i Azure AD for pålogging til admin/redaktørgrensesnittet (info.altinn.no)

**Comment by Herskis** [comment]
Følgende ble lagt inn for testperioden hvor altinn.cloud ble benyttet:
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/62640845/42c52ab1-40d5-46a2-9074-d30f4b4dbb5b)

**Comment by oyvindwh** [comment]
@Herskis, vi må ha hatt https://inte.altinn.cloud i listen også?

Dette er de nye domenene som skal logges på mot?
inte.info.altinn.no
prep.info.altinn.no
prod.info.altinn.no
info.altinn.no

**Comment by borresundberg** [comment]
@oyvindwh @Herskis - det er vel i praksis ingen SBL-miljøer som faktisk peker mot inte.altinn.cloud.  Alle testmiljøer i Altinn peker enten mot prep eller prod (prod og yt).  Når det er sagt så kan det vel ikke skade at vi en oppføring for inte i tilfelle vi skal bruke det en gang i fremtiden.

**Comment by Herskis** [comment]
@oyvindwh  
Inte.altinn.cloud ligger på en annen app registrering

Men nå er alle fire lagt inn, men ingen med signin-oidc, er det korrekt?

**Comment by haugsten** [comment]
Tror det er greit at de ligger uten signin-oidc. Men jeg ser at de er konfigurert i App Settings i paasportalen. 

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/6928826/f5497d1d-725e-4fda-bd83-5368a5ece2f5)

@WilhelmKXO 

For at det skal være mulig å logge inn på de nye url'ene må dette oppdateres i paasportalen og de må kjøres en ny deploy.

Alternativt kan det gjøres en kode endring slik at url hentes fra requesten.

https://docs.developers.optimizely.com/content-management-system/v11.0.0-cms/docs/integrate-azure-ad-using-openid-connect

```
        private void HandleMultiSiteReturnUrl(
            RedirectToIdentityProviderNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> context)
        {
            // here you change the context.ProtocolMessage.RedirectUri to corresponding siteurl
            // this is a sample of how to change redirecturi in the multi-tenant environment
            if (context.ProtocolMessage.RedirectUri == null)
            {
                var currentUrl = HttpContext.Current.Request.Url;
                context.ProtocolMessage.RedirectUri = new UriBuilder(
                    currentUrl.Scheme,
                    currentUrl.Host,
                    currentUrl.Port).ToString();
            }
        }
```

**Comment by haugsten** [comment]
@WilhelmKXO se kommentarer på pullrequesten. 

Bruk denne som eksempel på hvordan HandleMultiSiteReturnUrl kalles og postLogoutRedirectUri håndteres, så får vi det helt riktig.
https://docs.developers.optimizely.com/content-management-system/v11.0.0-cms/docs/integrate-azure-ad-using-openid-connect

**Comment by WilhelmKXO** [comment]
@haugsten Oppdatert PR

**Comment by haugsten** [comment]
@WilhelmKXO Approved!

**Comment by Herskis** [comment]
Da er [inte.info.altinn.no](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Finte.info.altinn.no%2F&data=05%7C01%7C%7C22953fcc563b4bc7d8d808dbd4c429dc%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638337711229252650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EWT6Kb6jHbLAvGhluCwJqG%2Ftgbz8NEPAhYNdh%2F%2BMRlA%3D&reserved=0) også lagt inn!

**Comment by ferkinx** [comment]
Er litt usikker på hva jeg ev. skal teste her - eller om noen andre skal gjøre det før saken flyttes til Done...
