### ISSUE TITLE
Relations /søk fungerer ikke

### ISSUE THREAD

**Issue by borresundberg** [Altinn/altinn-infoportal-optimizely#6]
### Description of the bug

Relations og søk fungerer ikke.  Trolig pga en bug som Kristoffer er kjent med.  

### Steps To Reproduce

 .

**Comment by davidsenkristoffer** [comment]
Status:

* Søket skal nå fungere. Årsak til feil var at byggesteget 'gitversionexecute' gjorde en oppdatering på assemblyversjon, som gjorde at sidetypene hadde en lavere assemblyversjon enn det som var lagret i databasen. 
* Jeg har fjernet noen Nuget-pakker som ikke er i bruk, og som skrev en del villedende feilmeldinger (Episerver.Telemetry.UI).
* Det gjenstår noe arbeid med å fikse skjemakatalogen.

Endringene er tilgjengelig i https://prod.altinn.cloud om ca. 30 minutter.

Til info @borresundberg @oyvindwh

**Comment by borresundberg** [comment]
@davidsenkristoffer / @oyvindwh  - er det prod.altinn.cloud vi bør forholde oss til nå i første omgang ift initiell testing/brøytekjøring?  Kan være greit om vi blir enige om ett miljø hvor redaktørene kan gjøre en første test.

**Comment by davidsenkristoffer** [comment]
Testinstruksjon:

Kontroller at både ordinært søk, hurtigsøk (? nede i høyre hjørne) og hjelpesøket fungerer:
https://prod.altinn.cloud/sok
https://prod.altinn.cloud/hjelp

Kontroller at skjemakatalogen vises som normalt.
https://prod.altinn.cloud/skjemaoversikt/

**Comment by ferkinx** [comment]
Saken med relations er løst, men det er fortsatt enkelte feil på søk, blant annet null treff i engelsk språkkanal. Jeg lukker denne issue-en, så oppretter vi heller konkrete issues på feil vi finner i søket.
