### ISSUE TITLE
SILJE: Redirects og endring av eksterne lenker

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#63]
### Description

Bestilling til Silje. Kan du hjelpe til med å rydde i døde lenker/legge inn nødvendige redirects og se på hvordan vi bør rette opp eksterne lenker inn til info.altinn.no?

Foreløpig inntil 10 timer - så kan vi diskutere videre.

### Additional Information

Arbeidet kan starte etter at databasen er flyttet over til DXP på onsdag/torsdag :)

**Comment by siljetjomlid** [comment]
- Wikipedia-linker er oppdatert

**Comment by ferkinx** [comment]
Supert - takk! (Skal jeg lukke denne da, eller var det mer du hadde planlagt her?)

**Comment by siljetjomlid** [comment]
- Redirects: Lagt inn redirects på brutte info.altinn.no-lenker i Optimizely.
