### ISSUE TITLE
Legg til interfacet IEnableBoosting til sudetypen SchemaPage

### ISSUE THREAD

**Issue by oyvindwh** [Altinn/altinn-infoportal-optimizely#65]
Da vil sidetypen dukke opp i listen for boosting.

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/c8a81a0f-3e94-44e9-b6cd-8801b8fc2fbd)

**Comment by WilhelmKXO** [comment]
https://dev.azure.com/digdir/altinn-infoportal/_git/altinn-infoportal/pullrequest/6519
Er det korrrekt at alle sider som arver på SchemaSitePageData skal ha boosting? i så fall kan jeg legge det der istedenfor på hver type.

**Comment by ferkinx** [comment]
Det spørsmålet bør vi nok rette til @haugsten :) 
Men tusen takk for at skjemasiden nå er på plass. Har allerede vektet den med en faktor på 1.6 

Siden jeg ikke helt forstår spørsmålet ditt, Wilhelm, venter jeg med å lukke saken - og flytter den til review.

**Comment by WilhelmKXO** [comment]
Det ble diskutert på sidelinjen, er fint å ha litt mer granulær styring slik det er i dag.
