### ISSUE TITLE
Optimizely Search søker ikke gjennom blokker med viktig info på skjemasidene

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#70]
### Description of the bug

- Søk på "høns"
- Det gir NULL treff
- Men ordet "høns" finnes på skjemasiden "Nytt/endre dyrehold" https://info.altinn.no/skjemaoversikt/mattilsynet/nyttendre-dyrehold/
Ordet "høns" ligger i en av blokkene på "Om skjema"-siden - som har trekkspillnavigasjon.

Det ser ut til at Optimizely-søket IKKE søker gjennom blokker med viktig innhold. (NB - det finnes kanskje noen blokker med generisk innhold som ikke skal gi treff også, men blokkene som vises som nedtrekkselementer skal iallfall indekseres.

![2023-10-26_21-33-10 (1)](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/1fc78ded-932c-4397-b648-48b670a505a7)

### Steps To Reproduce

1. Gå til søkefeltet på forsiden av https://info.altinn.no og søk på ordet "høns"
2. Ordet finnes i en nedtrekksblokk på "Om skjema"-siden for "Nytt/endre dyrehold" - og skal derfor gi ett treff (slik det gjør i det gamle Elastic-søket på altinn.no).

**Comment by WilhelmKXO** [comment]
@haugsten Jeg legger SchemaAccordianBlock inn i indekseringen. Har vi tilgang til å se nøyaktig hva som ble indeksert i den gamle løsningen slik at vi kan sammenligne? Tenker det kan være flere ting vi burde legge til.

**Comment by haugsten** [comment]
@WilhelmKXO Siden vi ikke bruker unifiedsearch må det gjøres på en litt annen måte, jeg skal lage et lite løsningsforslag.

**Comment by haugsten** [comment]
@WilhelmKXO Har sjekket inn kode for hvordan dette kan gjøres på PR [6520](https://dev.azure.com/digdir/altinn-infoportal/_git/altinn-infoportal/pullrequest/6520). 
Jeg har ikke oversikt over hvilke blokker og content areas som har vært indeksert og søkt i tidligere.

**Comment by WilhelmKXO** [comment]
@haugsten Skjønner, da er det bare å ta bort attributtet på schema accordion også ikke sant?

**Comment by WilhelmKXO** [comment]
Dette er nå rullet ut til pre-prod: https://prep.info.altinn.no/sok/?q=h%C3%B8ns


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/8856e9d5-9a0f-4bce-9163-122447cd3888)

**Comment by ferkinx** [comment]
Fortsatt er det innhold i blokker som ikke får treff. 

Vi har f.eks. søkt på ordet "Husdyrkonsesjonsregelverket". Ordet har en forekomst i trekkspillblokket "Mer om skjemaet" på siden [Altinn - Konsesjon til ervervsmessig produksjon av svin eller fjørfe](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Finfo.altinn.no%2Fskjemaoversikt%2Flandbruksdirektoratet%2Fkonsesjon-til-ervervsmessig-produksjon-av-svin-fjorfe%2F&data=05%7C01%7C%7Cb1cd07a271484a69f74d08dbd9e763c9%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638343360059845493%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F0%2BeDV%2BbsTdK4oVbsVmjvUK1ryn5J1%2Bd6pwZEVSlVU0%3D&reserved=0).
 
Søket gir ingen resultat på [https://info.tt02.altinn.no/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Finfo.tt02.altinn.no%2F&data=05%7C01%7C%7Cb1cd07a271484a69f74d08dbd9e763c9%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638343360060001792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ongI04nOyyHW6LbCz9CPioKyoNKDmkjdQjWpxiUto1A%3D&reserved=0) eller [https://prep.info.altinn.no/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprep.info.altinn.no%2F&data=05%7C01%7C%7Cb1cd07a271484a69f74d08dbd9e763c9%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638343360060001792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ny02jBunkQOxi6mp1e6jSYP5ArU6peww91fZ2qVAZV8%3D&reserved=0) eller i [PROD](https:info.altinn.no)

**Comment by haugsten** [comment]
Kan det være fordi at når jobben som indekserer innhold indekserer opp kjører den i engelsk kontekst. 

@WilhelmKXO Kan du teste å endre til følgende i ContentFromBlocks og kjøre indekserings jobben?

```
if(contentLoader.TryGet(item.ContentLink, schemaSitePageData.Language, out SchemaAccordianBlock schemaAccordianBlock))
 {
    str += $" {schemaAccordianBlock.SearchText()}";
}
```

**Comment by ferkinx** [comment]
@WilhelmKXO og @haugsten  
Jeg et på Forum for store offentlige nettsteder i dag og i morgen, så jeg har ikke rukket å teste grundig, men ser iallfall at de søkefrasene som er nevnt over her, fungerer nå. Takk for kjapp feilretting - ønsker at dette kjøres ut så snart som mulig. 
Vil det føre til ustabilitet i prod? Kan vi gjøre det nå, eller bør vi vente til i ettermiddag/kveld?

**Comment by WilhelmKXO** [comment]
@ferkinx Det skal ikke føre til ustabilitet i prod. Når vi deployer blir det opprettet en såkalt slot, her vil man kunne teste at siden fungerer før man fullfører selve deployen. Denne deler database med selve siten, så lenge det ikke er noen som gjør redaksjonelle endringer akkurat da vil det gå fint. For ordens skyld er det fint å gjøre det litt utenom de mest travle tidene.
