### ISSUE TITLE
Hvorfor ser sitemap.xml-filen så rotete og dårlig formatert ut?

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#71]
### Question

Hvorfor ser [sitemap.xml på Altinn](https://info.altinn.no/sitemap.xml) så rotete ut sammenlignet med f.eks. [DENNE sitemap-en.](https://www.knowit.no/no/sitemap.xml)

Her er Altinns sitemap:
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/9d0bd66e-89d8-494e-babb-f6b8ba7c9c17)

og her er KnowIT sin sitemap:
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/3bef31af-3682-452d-8e59-82760e761a47)

Vet vi at den som Optimizely-plugin-en lager har like god effekt hos Google som en mer velformatert sitemap?

**Comment by siljetjomlid** [comment]
I følge Google Search Console (og det faktum at sidene blir indeksert av Google), blir de plukket opp. Informasjonen ligger det, men formatet kan gjøre det vanskeligere enn det trenger å være for søkemotor å forstå strukturen. Det beste ville være å presentert et sitemap i vanlig XML-format.
Se eksempelvis [Forskningsrådets sitemap,](https://www.forskningsradet.no/sitemap.xml) som også er laget i Optimizely, med vanlig XML-struktur.

@WilhelmKXO og @JonasHildershavnKnowit , kan dere bistå med hvordan vi ordner dette for Altinn?

**Comment by oyvindwh** [comment]
Det er på grunn av størrelsen på sitemapen at den ser uformatert ut i nettleseren. Hvis man laster ned xml filen så ser den slik ut:

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/106393/240d4c2f-e8c8-4d6c-88b6-42ae939aeffc)

**Comment by siljetjomlid** [comment]
Da tenker jeg dette ikke er et problem. Maksgrense på et sitemap er 50.000 URLs, og så lenge formateringen fungerer i bunn (og blir lest, som den blir i dag) tenker jeg vi kan beholde filen som den er.
