### ISSUE TITLE
Robots.txt-fil blir ikke oppdatert og er mangelfull

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#74]
### Description of the bug

Robots.txt-filen, som ligger på https://info.altinn.no/robots.txt, er feil. Denne skal kunne oppdateres fra admin-grensesnittet, og det har jeg gjort. Der står det at oppdateringen har vært suksessfull (og jeg gjorde det også før torsdag + i dag):

Slik _skal_ .txt-filen se ut:
<img width="830" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/242a3282-9204-4b79-aca9-6caf9928f1b9">

Og slik _ser_ den ut:
<img width="473" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/eb18ea02-0b78-433b-9185-f424268cdfc1">

### Steps To Reproduce

1. Gå til https://info.altinn.no/robots.txt og sjekk at den ser ut slik angitt øverst

**Comment by WilhelmKXO** [comment]
Kan du se igjen nå? 

Det er tydeligvis flere valg i robots.txt editoren. 
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/2b7e65a3-e9f4-42e4-a580-34822830b43e)

Ser ut som om man kan bruke den første med * om man ikke har noe på de andre, men i dette tilfellet var den lille versjonen på info.altinn.no siten. Endret dette nå.

**Comment by ferkinx** [comment]
Supert - alt funker nå. Da var feilen "mellom stolen og tastaturet", som Børre pleier å si :)

Lynrask respons, Wilhelm. Veldig bra!
