### ISSUE TITLE
Sider får 400 - Bad Request statuskode, %URL% lagt til i URL

### ISSUE THREAD

**Issue by siljetjomlid** [Altinn/altinn-infoportal-optimizely#75]
### Description of the bug

18 sider får status-kode 400 Bad request grunnet "%URL%" i URL. Gjelder i hovedsak skjemaoversikt på norsk og engelsk.

Sidene det gjelder er:

https://info.altinn.no/starte-og-drive/stotteordninger/%URL%
https://info.altinn.no/en/start-and-run-business/support-schemes/%URL%
https://info.altinn.no/nn/starte-og-drive/stotteordningar/%URL%
https://info.altinn.no/skjemaoversikt/fylkeskommunene/selskapsvognloyve/%URL%
https://info.altinn.no/skjemaoversikt/kommunene/skjenkebevilling-for-skjenking-av-alkoholholdig-drikke/%URL%
https://info.altinn.no/skjemaoversikt/fylkeskommunene/drosjeloyve/%URL%
https://info.altinn.no/skjemaoversikt/kommunene/serveringsbevilling-/%URL%
https://info.altinn.no/nn/skjemaoversikt/fylkeskommunene/drosjeloyve/%URL%
https://info.altinn.no/nn/skjemaoversikt/kommunane/skjenkeloyve-for-skjenking-av-alkoholhaldig-drikke/%URL%
https://info.altinn.no/nn/skjemaoversikt/kommunane/serveringsloyve-/%URL%
https://info.altinn.no/nn/skjemaoversikt/fylkeskommunene/selskapsvognloyve/%URL%
https://info.altinn.no/en/forms-overview/municipalities/food-service-licence-/%URL%
https://info.altinn.no/en/forms-overview/municipalities/licence-to-serve-alcohol-application/%URL%
https://info.altinn.no/en/forms-overview/county-councils/limousine-service-operator-licences/%URL%
https://info.altinn.no/en/forms-overview/county-councils/drosjeloyve/%URL%
https://info.altinn.no/skjemaoversikt/fylkeskommunene/drosjeloyve-i-nordland-fylke/%URL%
https://info.altinn.no/en/forms-overview/county-councils/drosjeloyve-i-nordland-fylke/%URL%
https://info.altinn.no/nn/skjemaoversikt/fylkeskommunene/drosjeloyve-i-nordland-fylke/%URL%

### Steps To Reproduce

Linkene finnes på den ekte varianten av hver side. Eksempel, https://info.altinn.no/nn/skjemaoversikt/fylkeskommunene/drosjeloyve/%URL% finnes på https://info.altinn.no/nn/skjemaoversikt/fylkeskommunene/drosjeloyve/.

Feilen ser ut til å ligge i søkefeltet.

### Additional Information

<img width="1108" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/148449137/0b82aafb-f165-489e-81dc-ac9fbfad15cf">

**Comment by WilhelmKXO** [comment]
Årsaken til dette er at det er javascript som endrer verdiene markert med %. Siden crawleren ikke trigger når siden blir crawlet på må vi enten legge inn disallow på disse i robots.txt, eller se om vi kan flytte endringen til BE slik at dette ikke vises i det hele tatt. Dette er diskutert med Silje @ferkinx . 

Eksempel på endring for robots.txt:
User-agent: Googlebot
Disallow: /*%URL%

**Comment by ferkinx** [comment]
Skjønner egentlig ikke helt denne bug´en. Tror jeg må ha det inn med teskje muntlig, selv om jeg regner med at det dere foreslår er fornuftig :)

**Comment by siljetjomlid** [comment]
Vi la til en rad på dette i robots.txt sist uke. Når jeg sjekker i dag, ser det ut til å fungere. Sjekker igjen om en uke, men ingen %URL%-feil i nåværende rapport.

**Comment by siljetjomlid** [comment]
Undersøk igjen, ingen feil. Anser denne som lukket.
