### ISSUE TITLE
Feil på søket i infoportalen

### ISSUE THREAD

**Issue by GeirHerbertHorn** [Altinn/altinn-infoportal-optimizely#77]

**Comment by GeirHerbertHorn** [comment]
Vi har flere eksempler på søk som ikke viker i info portalen.
1.
Når man søker på 1021, et skjema fra Finanstilsynet,. Får man ikke treff.
Søker man på KRT-1021 får man treff.

Når man søker på "Innrapportering og tilskudd i forbindelse med slakting av rein", får man ingen treff.
Skjemaet ligger i skjema katalogen, når man går på etat og blar ned.

**Comment by ferkinx** [comment]
Dette er rart. Hvorfor får vi NULL treff ved søk på "slakting av rein", når skjemaet, når det står i tittelen på "Om skjema"-siden?

Det er også ønskelig at man får treff ved søk på skjemanummer UTEN etatskoden foran, slik det er påpekt foran, men på en måte som IKKE gjør resten av søket upresist.

**Comment by haugsten** [comment]
@ferkinx Jobben "Search & Navigation Content Indexing Job" har ikke kjørt etter at siste database backup ble gjennoprettet i forbindelse med go live. Etter å ha kjørt denne får jeg nå treff på "Innrapportering og tilskudd i forbindelse med slakting av rein" og "slakting av rein". Så det kan se ut som indeksen med data fra test perioden ikke inneholdt alle sider. Har satt opp jobben til å kjøre en gang i uken slik at det ryddes opp i indeksen hvis det oppstår feil ved publisering ol. 

Skal se nærmere på hvordan vi best kan håndtere søk på skjemanummer.

**Comment by haugsten** [comment]
@WilhelmKXO Det enkleste er kanskje å lage en extension metode på SchemaSitePageData som returnerer nummeret etter tegnet - som en string. Inkluder metoden med IncludeField i FindInitialization.cs og i søket i metoden InfieldsWithRelativeImportance.

```
        public static string SchemaCodeNumber(this SchemaSitePageData page)
        {
            var str = "";

            if(string.IsNullOrWhiteSpace(page.SchemaCode) == false && page.SchemaCode.Contains("-"))
            {
                str = page.SchemaCode.Substring(page.SchemaCode.LastIndexOf('-') + 1);
            }
            
            return str;
        }
```

**Comment by ferkinx** [comment]
@haugsten @WilhelmKXO Bra, men er det også slik at nypublisert innhold automatisk pushes ut i søkeindeksen?

**Comment by WilhelmKXO** [comment]
@haugsten https://dev.azure.com/digdir/altinn-infoportal/_git/altinn-infoportal/pullrequest/6528

**Comment by ferkinx** [comment]
Her er jeg litt seint ute, siden jeg er på Digdir-samling på Plaza. Veldig bra å få skilt ut skjemanummer-strengen i eget felt som kan vektes sammen med de andre feltene, men jeg skulle også ønske at vi kan få enda et felt, dvs. både

KRT-1079 (som er det som står i skjemanummerfeltet i dag)
1079 (som jeg forstår ligger i koden over)
KRT1079 (som vi ser at også mange søker på)

**Comment by haugsten** [comment]
@WilhelmKXO Legger du til det siste feltet som Jørgen nevner og gir begge de to nye feltene samme boost som SchemaCode.

`.InField(x => ((SchemaSitePageData)(object)x).SchemaCodeNumber(), ri.SchemaCode)`

**Comment by WilhelmKXO** [comment]
@haugsten vil dette fungere? Eller må vi lage en ny metode og behandle det som om det er et eget felt?

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/2205245b-6e24-450f-b59d-51f2b100f8eb)

**Comment by haugsten** [comment]
@WilhelmKXO Kan like godt ha de i samme felt, men må vel være .Replace("-", string.Empty)

**Comment by haugsten** [comment]
> @haugsten @WilhelmKXO Bra, men er det også slik at nypublisert innhold automatisk pushes ut i søkeindeksen?

Ja ved publisering (av nytt og gammelt innhold), sletting osv. pushes det til indeksen.

**Comment by WilhelmKXO** [comment]
Var det det skulle være ja. PR oppdatert nå

**Comment by ferkinx** [comment]
Får fortsatt ikke treff ved søk på "Husdyrkonsesjonsregelverket", enda ordet forekommer i trekkspill-feltet "Mer om skjemaet" for skjemaet [Konsesjon til ervervsmessig produksjon av svin eller fjørfe](https://info.tt02.altinn.no/skjemaoversikt/landbruksdirektoratet/konsesjon-til-ervervsmessig-produksjon-av-svin-fjorfe/)

**Comment by GeirHerbertHorn** [comment]
Det må være noe mer som henger et sted.
Jeg oppdaterte en tekst på 
https://info.altinn.no/skjemaoversikt/digitaliseringsdirektoratet/felles-datakatalog/
Dette gjorde jeg 08:49 i dag.
Etter over en time er ikke teksten oppdatert i portalen.

**Comment by haugsten** [comment]
@GeirHerbertHorn Kan ikke se at siden https://info.altinn.no/skjemaoversikt/digitaliseringsdirektoratet/felles-datakatalog/ er endret siden 24. januar. Hva er det som ikke er oppdatert? Er det relatert til feil på søket?

**Comment by GeirHerbertHorn** [comment]
@haugsten Jeg la inn ny tekst under Hvem kan bruke tjenesten, og denne er ikke oppdatert, Jeg gjorde det 10.10 i dag.

Ny tekst som ble lagt inn: 
For å få tilgang, må du ha riktig rettighet eller rolle i Altinn.

*  Enkeltrettighet: «Felles datakatalog – alle kataloger – skrivetilgang», «Felles datakatalog – alle kataloger – lesetilgang» eller «Felles datakatalog – alle kataloger –  virksomhetsadministrator». *

Rolle: Kommunale tjenester

Tjenesten krever innlogging med ID-porten (sikkerhetsnivå 3).

**Comment by WilhelmKXO** [comment]
@GeirHerbertHorn Kan du prøve igjen? får du en feilmelding når du trykker publiser?

**Comment by WilhelmKXO** [comment]
@ferkinx har rullet ut en oppdatering til Prep nå, kan du prøve søket igjen?

**Comment by GeirHerbertHorn** [comment]
Sjekker

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO Får ikke feilmelding når jeg skal publisere.

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO @ferkinx Søk viker ikke. Testet 1021 får ingen treff

**Comment by WilhelmKXO** [comment]
@GeirHerbertHorn Hvor tester du? Har ikke rullet ut noe til produksjon enda. Dette er i prep.info.altinn.no:


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/50671178-8905-43e0-b4dc-971beaca09b7)


Kan du gi meg mer informasjon angående oppdatering av tekst som ikke går?

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO Min feil, tester igjen.

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO @haugsten @ferkinx Denne saken handlet om feil i søk, det andre spøsrmålet var feil i publisering.

Jeg har laget ny sak på dette, siden dette ikke har noe med søk å gjøre.

**Comment by ferkinx** [comment]
@WilhelmKXO Da tenker jeg at denne kan kjøres ut i PROD så raskt som mulig, f.eks. fredag morgen
