### ISSUE TITLE
Infoportal oppdateres ikke når det gjøres endringer.

### ISSUE THREAD

**Issue by GeirHerbertHorn** [Altinn/altinn-infoportal-optimizely#79]

**Comment by GeirHerbertHorn** [comment]
Gjelder PROD 
Jeg har lagt inn en endring på https://info.altinn.no/skjemaoversikt/digitaliseringsdirektoratet/felles-datakatalog/ under overskriften Hvem kan bruke tjenesten. 

Jeg legger inn endringen og klikker på publiser. 

Endringen kommer ikke ut i portalen. 
Endringen ble først gjort 01.11.2023 08:49. 

Tekst som skal ligge der etter endring:
"For å få tilgang, må du ha riktig rettighet eller rolle i Altinn.

Enkeltrettighet: «Felles datakatalog – alle kataloger – skrivetilgang», «Felles datakatalog – alle kataloger – lesetilgang» eller «Felles datakatalog – alle kataloger –  virksomhetsadministrator».

Rolle: Kommunale tjenester

Tjenesten krever innlogging med ID-porten (sikkerhetsnivå 3)."

**Comment by GeirHerbertHorn** [comment]
Når jeg gjør den samme endringen i TT02 virker det.

**Comment by WilhelmKXO** [comment]
Jeg gjennomførte endringen nå uten problemer. Kan du verifisere at det er dette som skal stå?


![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/041bfc2e-c7ed-4ae4-a33d-bfc3d5a7655d)


I loggen stod det at det ikke var endring der siden januar. Trykket du ved siden av feltet slik at informasjonen kunne bli oppdatert før publisering?

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO Ser ikke ut for at dette er hekt riktig. 
På tjenesten https://info.altinn.no/nn/skjemaoversikt/digitaliseringsdirektoratet/felles-datakatalog/ oppdaterte jeg teksten under Hvem skal bruke skjemaet på nynorsk og engelsk. Disse er ikke oppdatert enda.

**Comment by WilhelmKXO** [comment]
Du sier at du oppdaterer teksten og trykker publiser, altså, at du skriver endringen inn i riktekst feltet, så trykker på siden og ser at det står det blir lagret en draft og blå boks med publiser. Deretter trykker du publiser. Er dette riktig?

**Comment by GeirHerbertHorn** [comment]
@GeirHerbertHorn  ja det er riktig

**Comment by ferkinx** [comment]
@GeirHerbertHorn Er det flere enn deg som opplever problemer ved publisering? Kan det ev. hjelpe å slette cookies etc. i nettleser?

Jeg har nettopp gjort endringer og publisert driftsmelding på forsiden...

**Comment by GeirHerbertHorn** [comment]
@ferkinx Er dette riktig lenke i Episerver for PROD?

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO Kan du legge ut url til Episerver i PROD og TT02?

Jeg begynner å lure om jeg har feil url.

**Comment by WilhelmKXO** [comment]
Det ser ut til at du har veil lenke til prod ja! 

Nå brukes info.altinn.no/episerver/cms
TT02 er da info.tt02.altinn.no/episerver/cms. Dette er egentlig bare en lenke til pre-prod, altså prep.info.altinn.no.

**Comment by GeirHerbertHorn** [comment]
Ja der har du det, jeg kommer ikke inn på  info.tt02.altinn.no/episerver/cms, men det er kanskje noe annet.

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO Dere kan lukke denne.
