### ISSUE TITLE
To nye feil/rariteter i søket?

### ISSUE THREAD

**Issue by ferkinx** [Altinn/altinn-infoportal-optimizely#82]
### Description of the bug

1. I følge søkestatistikken, er det mange søk på lista over "Searches without relevant hits". Jeg forstår rett og slett ikke hvorfor disse søkene ikke fører til klikk på relevante treff. Er det noe feil her?

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/951cca3f-c704-4da7-9521-baec61e52ac5)
Dette kan da ikke stemme?
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/2dd8d8e2-4d74-4b1f-bd1d-fde88706dbc9)

2. Under SØK - Søkeinnstillinger i Admin-grensesnittet, virker det som om Hit Boost Scale-verdien jeg setter blir nullstilt når jeg går ut av søkeinnstillinger og kommer tilbake igjen. Virker Hit boost som den skal? Og vekting?
![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/fa33a0b3-87f7-41fe-924f-5f9b4b3ae2bc)

### Steps To Reproduce

---

**Comment by WilhelmKXO** [comment]
Har tittet litt på dette nå.
1: Mistenker at årsaken til dette er at sidene ikke heter det samme som søketreffet. Ser at søk på A06 oftest trykker på Avstemmingsinformasjon. Tror ikke søket erkjenner at dette er samme og korrekt, at de burde da være en side som heter A06.

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/147068285/b853af67-06f4-41dd-956b-6c2603b38f30)

2: Her vises kun første desimalen, kan være at 0.01 blir lagret korrekt, men siden visningen bare viser første desimalen forsvinner den litt. Ser på koden at den burde bli lagret korrekt selv om den ikke vises korrekt.

**Comment by ferkinx** [comment]
Hvis det er slik du antyder på pkt. 1, er jo den statistikken totalt meningsløs. De som søker på a06 eller 1306 er jo virkelig de som vet akkurat hvor de skal, og som derfor søker på skjemanummeret i stedet for navnet. Hvis Optimizely mener at et søk ikke gir relevante treff når søkefrasen ikke er nevnt i tittelen, har de ikke skjønt mye av hva relevante treff betyr. Er søkestatistikken virkelig så teit, @haugsten ?

 Pkt. 2: Kan dere endre feltet slik at det vises minst to desimaler - eller gjerne tre? Det er nemlig veldig aktuelt å velge brattere Hitboost-kurve enn det som er mulig med bare en desimal:

![Image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/64840623/a904c46b-4924-4750-bc81-30d34e39ded0)

**Comment by WilhelmKXO** [comment]
@haugsten Dette er nå rullet ut til integration. Bare å teste

**Comment by haugsten** [comment]
@WilhelmKXO @ferkinx Ser ut til at "Searches without relevant hits" telles riktig på inte nå.

@ferkinx Når det gjelder f.eks. aksjonærregisteret som du så i listen over søk uten treff tror jeg det kommer av at det lenkes til "Avgrens treffene" med "Altinn hjelpesider 0" som blir et søk som ikke gir treff. Hvis noen klikker denne ser det ut til at det noen ganger registreres som null treff. Det bør kanskje ikke være mulig å klikke på filter som gir 0 treff.

![image](https://github.com/Altinn/altinn-infoportal-optimizely/assets/6928826/b9969893-2ff6-4d50-9436-9f41c90f315d)

**Comment by ferkinx** [comment]
Ser greit ut, tror jeg. Vanskelig med skikkelig test før vi er i prod. Så kjør den ut sammen med URL-fiksen så snart du kan, @WilhelmKXO

**Comment by WilhelmKXO** [comment]
@haugsten Denne er nå i produksjon. Har du mulighet til å lage en ny sak på det med "Altinn hjelpesider"? Ønsker ikke at denne saken som originalt var noe annet skal bli hengende med flere deler hvorav noe er fikset.
