### ISSUE TITLE
URL til Innboks er feil.

### ISSUE THREAD

**Issue by GeirHerbertHorn** [Altinn/altinn-infoportal-optimizely#83]

**Comment by GeirHerbertHorn** [comment]
Vi har noen skjema som instansieres fra TE. Når de går inn på skjemasiden er det en URL som peker til Innboks slik at bruker finner skjema.

Eks:
https://info.altinn.no/skjemaoversikt/tolletaten/deklarasjonsoversikten/

Når man her klikker på Til innboksen, skal man komme til innboks, men det kommer til en side som ikke finnes.

Det er flere tjenester som har denne funksjonen.

**Comment by GeirHerbertHorn** [comment]
Update 
Når man her klikker på Til innboksen, skal man komme til innboks, hvis man ikke er innlogget skal man komme til IDPorten.

**Comment by WilhelmKXO** [comment]
@GeirHerbertHorn Dette er rullet ut til preprod/tt02. Vennligst test så skal vi se på å få det ut til produksjon asap.
https://info.tt02.altinn.no/skjemaoversikt/tolletaten/deklarasjonsoversikten/

**Comment by GeirHerbertHorn** [comment]
@WilhelmKXO Dette virker nå som det skal.
