### ISSUE TITLE
Design og innhold chat på altinn.no

### ISSUE THREAD

**Issue by alisekjelling** [Altinn/altinn-infoportal-optimizely#87]
**Implementering:**
Seksjonsleder på Altinn brukerservice ønsker at vi skal få chatten i produksjon så raskt som mulig, selv om det innebærer at den først bare kommer i Infoportalen FØR den kommer i SBL. Hun er inneforstått med at brukerne da ikke vil finne chatten på sidene under innboks eller profil/delegering etc., men ønsker likevel å få chatten ut så kjapt som mulig. / Siden jeg ikke fant noen egen issue for selve implementeringen, gjenbrukte jeg denne :) @ferkinx 

**Åpne spørsmål:**

- Hvilke sider skal den være på? 
- Hvor på siden?
- Hvor mye skal de gjøre før de får snakket med et menneske? Navn og e-post slik som id-porten?
- Innhold / mal for svar
- Hva kan du spørre om?
- Trenger vi skriv til oss / e-post?
- Redesigne hjelpesidene/footer
- Hva skal hjelpesiden være og for hvem?
- Når skal man få hjelp? 

----

**Prosess:** 

- Finne eksempler på hvordan andre har løst chat
- Felles arbeidsøkter hvor vi utforsker mulige løsninger
- Bli enig om et forslag vi kan presentere for teamet og med ABS (frist 17.11). Målet er at dette kan la seg gjøre på kort sikt med implmentering før jul.

**Comment by thordfoss** [comment]
Førsteutkast på chat. Sikkert mye som må justeres, men tror det er et ok utgangspunkt for testing og diskusjon. God jul!

https://www.figma.com/file/hWGwZdap6M7M3NpD145N5B/Hjelp-og-chat?type=design&node-id=56%3A368&mode=design&t=fcmKej153hLffqNQ-1

**Comment by WilhelmKXO** [comment]
Denne ligger nå ute i integration miljøet. Feedback fra Thord etter testing: https://www.figma.com/design/RSqfztSZHCbMn0tvqU9wtD/Designkorrektur-Chat?node-id=0-1

**Comment by ferkinx** [comment]
Testet OK, spesielt siden vi nå kan aktivere og deaktivere chatten (inkl. javascriptet) redaksjonelt.
