### ISSUE TITLE
Sider på https://info.tt02.altinn.no indeksert av Google

### ISSUE THREAD

**Issue by siljetjomlid** [Altinn/altinn-infoportal-optimizely#88]
### Description of the bug

Det finnes ca 65 URLer fra https://info.tt02.altinn.no som har blitt indeksert av Google.

Rett før flytt fra www.altinn til info.altinn skal dette ha blitt tatt hånd om i robots.txt, men når jeg sjekker i dag er robots.txt gjensatt til standard Optimizely. Denne blokkerer ikke søkemotorer fra crawling.

<img width="440" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/148449137/3c6c8957-5e38-4bf3-a5b8-1b55faac87b2">

Her må vi legge til følgende i https://info.tt02.altinn.no robots.txt-fil:
```
User-agent: *
Disallow: /
```

Det kan med fordel også legges til 
```
<head>
    <meta name="robots" content="noindex, nofollow">
</head>
```

### Steps To Reproduce

1. Google "site:https://info.tt02.altinn.no" for å se indeksering
<img width="601" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/148449137/0122f7d0-5c35-44e2-b35f-ea9877ced448">

2. Inne i Search Console ser vi i 404-rapporten at Google prøver å indeksere innhold fra https://info.tt02.altinn.no. Det er 37 sider her med 404-status.
<img width="965" alt="image" src="https://github.com/Altinn/altinn-infoportal-optimizely/assets/148449137/0ebffd96-4b78-40c1-80e9-005502d8fbac">

**Comment by WilhelmKXO** [comment]
Er endret nå. Det var ikke satt riktig for alle sites i preprod miljøet.
